name: Build and Deploy to Nexus

on: [push]

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 8
              uses: actions/setup-java@v4
              with:
                java-version: '8'
                distribution: 'adopt'
                cache: maven
            - name: Build with Maven and Deploy
              run: mvn deploy --settings settings.xml
              env:
                NEXUS_USER: ${{ secrets.NEXUS_USER }}
                NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
                DISTRIBUTION_URL: ${{ secrets.DISTRIBUTION_URL }}
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v3
              with:
                token: ${{ secrets.PAT }}
                repository: meher-liatrio/spring-petclinic
                event-type: dispatch-event